
name: Update_Python

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: wifiinfo.py

    - name: Generate code coverage report
      run: coverage run --source=. -m pytest && coverage report

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Atualizar repositório"
        git push
